### ISSUE TITLE
can't deploy even with s2, s3 web app plan

### ISSUE THREAD

**Issue by imanebrams** [OfficeDev/microsoft-teams-apps-timetally#17]
dear team, 
I tried many times to deploy time tally following exactly the steps on deployment guide, I got the deployment failed error with this message : WARNING: The data being saved is truncated to 1024 characters.
installing entity framework packages
ERROR: Access to the registry path is denied.
Failed to add 'C:\local\UserProfile\.dotnet\tools' to the PATH environment variable. Add this directory to your PATH to use tools installed with 'dotnet tool install'.
Can you please assist. 
Thanks

**Comment by AsharmaS4** [comment]
Hello, were you able to resolve this, I am getting the same error.
