### ISSUE TITLE
Deployment Guide - appbaseurl missing

### ISSUE THREAD

**Issue by kylescenik** [OfficeDev/microsoft-teams-apps-timetally#2]
In the deployment guide, Step 4, action 4 it mentions 
"Replace <appbaseurl> placeholder with the Azure front door URL created i.e.'https://[BaseResourceName].azurefd.net'. For example, if you chose timetally then the appbaseurl will be https://timetally.azurefd.net."

This does not exist in Manifest\manifest.json

**Comment by v-smahaj** [comment]
Thank you for reporting this. We have updated the deployment guide to resolve mentioned issue. Closing this issue.
