### ISSUE TITLE
Step 2: Deploy to your azure subscription

### ISSUE THREAD

**Issue by iamnirajpandey** [OfficeDev/microsoft-teams-apps-timetally#4]
i am getting the below error everytime whenever i am trying to deploy the app on azure portal. i have tried almost 7 - 8 times but the error is always the same as below.

Summary:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n }\r\n}"}]}

Raw Error:
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    }
  ]
}

i am literally lost as what i am doing wrong while deploying this app, would request if anyone could help me overcome the issue asap.

Thanks in advance,

**Comment by v-smahaj** [comment]
Can you try upgrading App Service plan to S3 and sync again.
Let us know if issue still persists.
