### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by andrewgeer** [OfficeDev/microsoft-teams-apps-timetally#5]
![error](https://user-images.githubusercontent.com/15823710/119123668-b3ebd480-ba27-11eb-8607-3dc79d57d2dc.jpg)
Hi attached screen shot during deployment, error is with Microsoft.Web/sites/sourcecontrols failing to deploy with status Conflict,

Thanks
Andrew

**Comment by v-smahaj** [comment]
Can you try with higher App Service Plan tier like S2 or S3. You can reduce tier back to S1 once deployment is complete.
Let us know if issue still persists.
