### ISSUE TITLE
Problem with manifest.json

### ISSUE THREAD

**Issue by vajdis** [OfficeDev/microsoft-teams-apps-timetally#7]
Hello, 
I followed exactly every step in your deployment guide (2x, since I wanted to be sure I did nothing wrong in the first try before I post an issue), but the manifest.json of the app is probably different than what is expected. There is no botId, appDomain or clientId value to change. Also you dont specify what the en-US.json file which has to be in the .zip of an app should do or contain. I quite like the deployment guide, since its nice and detailed but "step 4" seems a bit unclear to me. Could I ask for help with the step? :) 

Sincerely,

Vaclav

**Comment by Xorserd** [comment]
Download the codes from the repo. Manifest.json file with the parameters you require are included here

**Comment by vajdis** [comment]
I see, thank you :) I didn´t check the repo since there was already some "manifest.json" in Azure portal
