### ISSUE TITLE
Cannot do anything in Teams

### ISSUE THREAD

**Issue by tamasv83** [OfficeDev/microsoft-teams-apps-timetally#8]
Dear All,

I've deployed this app in our Teams environment based on the deployment guide found here. 
While deploying everything went fine. Now users can add TimeTally app in Teams but there is nothing to click on. All tabs are empty in TimeTally bot.
All tabs looks like the attachment for all users.
What am I did wrong or what is missing? 
Thank you!
![timetally](https://user-images.githubusercontent.com/86463545/123384577-dc21a280-d594-11eb-8936-d18fab400a81.png)

**Comment by tamasv83** [comment]
I've chaged the url in manifest.json and now I getting this: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by tamasv83** [comment]
This resolved with fully reinstalling.

**Comment by AsharmaS4** [comment]
Can you please help me understand how you resolved this? I have tried redeploying numerous times from scratch, but I keep getting the exact same error on teams.
